# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:lts

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
    - docker:dind

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    
build package:
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  image: node:lts
  stage: deploy
  before_script:
    - apt update && apt install jq -y
  script:
    - npm ci
    - npm run build
    - mv public public-vue
    - mv dist public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
    - |
      echo "{ \"build_date\": \"$(date)\", \"commit_sha\": \"$CI_COMMIT_SHORT_SHA\" }" | jq . > public/build-info.json
    - cp public/index.html public/404.html
    
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - public
  only:
    - master
